import { useEffect, useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { CheckSquare } from "lucide-react";

const AI_PANEL_GUIDE_KEY = "ai-panel-guide-seen";

/**
 * One-time "how to use AI" welcome dialog.
 * Reads a localStorage flag on mount — if the user has never seen it,
 * it auto-opens. When they close it, the flag is written so it never
 * appears again.
 */
const AiGuideDialog = () => {
  const [open, setOpen] = useState(false);

  // On mount: check if this user has already seen the guide
  useEffect(() => {
    const alreadySeen = window.localStorage.getItem(AI_PANEL_GUIDE_KEY);
    if (!alreadySeen) {
      setOpen(true);
    }
  }, []);

  const handleOpenChange = (nextOpen: boolean) => {
    setOpen(nextOpen);
    // When closing (nextOpen = false), mark it as seen so it never shows again
    if (!nextOpen) {
      window.localStorage.setItem(AI_PANEL_GUIDE_KEY, "true");
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="desktop-dialog assistant-guide-dialog max-w-sm">
        <DialogHeader>
          <DialogTitle>How to use AI Assistant</DialogTitle>
          <DialogDescription className="sr-only">
            Quick tips for chatting with the current note and using AI selection actions.
          </DialogDescription>
        </DialogHeader>
        <div className="assistant-guide-content space-y-4">
          <div className="assistant-guide-list space-y-3">
            <div className="flex items-start gap-2.5 text-sm leading-relaxed text-[var(--text-strong)]">
                <CheckSquare size={16} className="shrink-0 mt-0.5 text-[var(--accent-strong)]" />
                <span>Ask a question to chat about the current note.</span>
            </div>
            <div className="flex items-start gap-2.5 text-sm leading-relaxed text-[var(--text-strong)]">
                <CheckSquare size={16} className="shrink-0 mt-0.5 text-[var(--accent-strong)]" />
                <span>Select text first if you want help with a specific section.</span>
            </div>
            <div className="flex items-start gap-2.5 text-sm leading-relaxed text-[var(--text-strong)]">
                <CheckSquare size={16} className="shrink-0 mt-0.5 text-[var(--accent-strong)]" />
                <span>Use quick actions for fast rewrite, summary, or improvement passes.</span>
            </div>
          </div>
          
          <div className="mt-4 p-3 bg-[var(--surface-ghost)] rounded-lg text-xs leading-5 text-[var(--muted-text)] border border-[var(--divider)]">
            <p className="font-semibold text-[var(--text-strong)] mb-1 flex items-center gap-1.5">
                💡 Important Note:
            </p>
            AI can make mistakes! Please double-check any data or information generated by the AI before using it for critical tasks.
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default AiGuideDialog;
