const states = [
    {id:1,text:"Plotting"},
    {id:2,text:"Procrastinating"},
    {id:3,text:"Overthinking"},
    {id:4,text:"Cooking"},
    {id:5,text:"Manifesting"},
    {id:6,text:"Scheming"},
    {id:7,text:"Debugging"},
    {id:8,text:"Glitching"},
    {id:9,text:"Compiling"},
    {id:10,text:"Negotiating"},
    {id:11,text:"Buffering"},
    {id:12,text:"Vibing"},
    {id:13,text:"Overengineering"},
    {id:14,text:"Hallucinating"},
    {id:15,text:"Optimizing"},
    {id:16,text:"Guessing"},
    {id:17,text:"Refactoring"},
    {id:18,text:"Brewing"},
    {id:19,text:"Decoding"},
    {id:20,text:"Hyperventilating"},
    {id:21,text:"Processing"},
    {id:22,text:"Pondering"},
    {id:23,text:"Calculating"},
    {id:24,text:"Summoning"},
    {id:25,text:"Spawning"},
    {id:26,text:"Improvising"},
    {id:27,text:"Encrypting"},
    {id:28,text:"Corrupting"},
    {id:29,text:"Rebooting"},
    {id:30,text:"Dissociating"},
    {id:31,text:"Scrambling"},
    {id:32,text:"Reconsidering"},
    {id:33,text:"Rationalizing"},
    {id:34,text:"Yapping"},
    {id:35,text:"Cooked"},
    {id:36,text:"Locking in"},
    {id:37,text:"Brainstorming"},
    {id:38,text:"Simulating"},
    {id:39,text:"Regretting"},
    {id:40,text:"Transcending"},
];

export const getThinkingState = () => states[Math.floor(Math.random() * states.length)];